# Page settings
baseurl = "https://muharch.github.io"
title = "MuhArch - Enjoy the beauty"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "MuhArch"
    home = "MuhArch"
    work = "Screenshots"
   services = "Features"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    #  postpended links
    [[menu.postpend]]
      url = "https://sourceforge.net/projects/muharch/files/muharch-bspwm/muharch-082620-bspwm-x86_64.iso/download"
      name = "Download"
      weight = 0
  
  # Hero section
  [params.hero]
    title = "MuhArch - Arch Linux made beautiful."
    subtitle = 'MuhArch provides a fully working minimal Arch Linux installation with an easy installer. There are a bunch of wallpapers in the Wallpaper folder and colorschemes are based on them. Simply do "wal -i /path/to/img" to change it to whatever you please. This is a minimal medium tailored to MY needs and usage. Further customization and changes are encouraged and expected from the user.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Wiki"
    description = "For any technical inquires please refer to the Arch Wiki or send me an e-mail (it's down there)"
    url = "https://wiki.archlinux.org"
    button = "Arch Wiki"
    icon = "icon-book-open"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Download"
    description = "Cheatsheet for the keybindings can be found at the SF page, the user password is muhmuh, send the feedbacks to my e-mail."
    url = "https://sourceforge.net/projects/muharch/files/muharch-bspwm/muharch-082620-bspwm-x86_64.iso/download"
    button = "Click Here"
    icon = "icon-cloud-download"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Github Page"
    description = "To inspect what you are installing and see the source code for yourself, take a look at the Github page."
    url = "https://github.com/bar1917/muharch-iso"
    button = "Github"
    icon = "icon-social-github"
    img = "img_10.jpg"


  # Work section
  [params.work]
    enable = true
    title = "Screenshots"
    footertext = 'Wallpapers are included'

    [[params.work.row]]
      img = "drive.png"
      alt = "Image2"
      title = "Screenshot"
      subtitle = "Drive"

    [[params.work.row]]
      img = "sunsetgirl.png"
      alt = "Image2"
      title = "Screenshot"
      subtitle = "Sunsetgirl"

    [[params.work.row]]
      img = "space.png"
      alt = "Image3"
      title = "Screenshot"
      subtitle = "Spaaace"

    [[params.work.row]]
      img = "busy.jpg"
      alt = "Image4"
      title = "Screenshot"
      subtitle = "Busy"

  # Footer section
  [params.footer]
    enable = true
    links = [
        ["icon-envelope", "mailto:muharch@protonmail.com"]
      ]
